#ifndef PARAM_CONFIG_H
#define PARAM_CONFIG_H

/* 用于启动日志和测试报告的参数包版本 */
#define PARAM_VERSION_STR "demo_v0.1_baseline"

/* 机械校准参数 */ 
#define PARAM_YAW_CHASSIS_ALIGN_ECD 2711
#define PARAM_PITCH_HORIZON_ECD 3412
#define PARAM_PITCH_MAX_ANGLE 30.0f
#define PARAM_PITCH_MIN_ANGLE -30.0f

/* 云台 YAW 轴电机控制器参数 */
#define PARAM_YAW_ANGLE_KP 0.3f
#define PARAM_YAW_ANGLE_KI 0.8f
#define PARAM_YAW_ANGLE_KD 0.005f
#define PARAM_YAW_ANGLE_INT_LIMIT 20.0f
#define PARAM_YAW_ANGLE_MAX_OUT 20.0f

#define PARAM_YAW_SPEED_KP 1200.0f
#define PARAM_YAW_SPEED_KI 0.0f
#define PARAM_YAW_SPEED_KD 3.0f
#define PARAM_YAW_SPEED_INT_LIMIT 16000.0f
#define PARAM_YAW_SPEED_MAX_OUT 16000.0f

/* 云台 PITCH 轴电机控制器参数 */
#define PARAM_PITCH_ANGLE_KP 1.0f
#define PARAM_PITCH_ANGLE_KI 0.0f
#define PARAM_PITCH_ANGLE_KD 0.005f
#define PARAM_PITCH_ANGLE_INT_LIMIT 10.0f
#define PARAM_PITCH_ANGLE_MAX_OUT 10.0f

#define PARAM_PITCH_SPEED_KP 0.8f
#define PARAM_PITCH_SPEED_KI 0.0f
#define PARAM_PITCH_SPEED_KD 0.0f
#define PARAM_PITCH_SPEED_INT_LIMIT 0.1f
#define PARAM_PITCH_SPEED_MAX_OUT 1.0f

/* 前馈与保护 */
#define PARAM_YAW_SPEED_FEEDFORWARD_SCALE 500.0f
#define PARAM_YAW_SPEED_FEEDFORWARD_LIMIT 10.0f
#define PARAM_YAW_CURRENT_FEEDFORWARD_ABS 500.0f

/* 视觉输入限制 */
#define PARAM_VISION_YAW_ERR_MIN -100.0f
#define PARAM_VISION_YAW_ERR_MAX 100.0f
#define PARAM_VISION_PITCH_ERR_MIN -100.0f
#define PARAM_VISION_PITCH_ERR_MAX 100.0f
#define PARAM_VISION_DIST_MIN 500.0f
#define PARAM_VISION_DIST_MAX 1560.0f

#endif /* PARAM_CONFIG_H */
